#!/bin/sh
# fetch-inputs.sh -- download, verify and generate the benchmark inputs into
# testdata/bench/ (gitignored). Idempotent: a second run re-verifies the
# downloads and skips what is already in place. A checksum mismatch aborts.
#
# Sources, pins and licences (also written to testdata/bench/SOURCES.md):
#
#   xrechnung/  KoSIT XRechnung visualization v2026-08-31
#               (github.com/itplr-kosit/xrechnung-visualization, commit
#               e158048ec6774cd4837744b21ca34dc95ba14862), Apache-2.0;
#               invoices from KoSIT xrechnung-testsuite v2026-08-31
#               (commit 44c3905c69ca236aa3b94c04be1b7e9bd066ba03), Apache-2.0.
#   peppol/     OpenPEPPOL peppol-bis-invoice-3 v3.0.20 (commit
#               261c458474e27d58a25be629cccac28883171c92). No licence file:
#               the CEN-EN16931 rules carry "EUPL-1.2"; the PEPPOL rules are
#               (c) OpenPeppol AISBL, "reproduced with permission from CEN",
#               redistribution needs OpenPeppol's consent -- fetched, never
#               committed. Compiled to XSLT with SchXslt 1.10.1
#               (codeberg.org/SchXslt/schxslt, commit
#               17f63a42c2d417206e1289cf767359c4fa047919), MIT.
#   xmark/      XMark xmlgen (CWI, projects.cwi.nl/xmark, unix.c, reports
#               itself as 0.92), public domain per the CWI download page;
#               queries (xmlquery.txt) and auction.dtd from the same page,
#               no licence stated. Pinned by SHA-256 of each file.
#   parse/      generated by bench/gen (this repository, MIT), fixed seed.
#   docbook/    DocBook 5.2 schema (github.com/docbook/docbook release 5.2,
#               commit 7bf26df21266c00d38ea1d3033bcd70c2b280a59), DocBook
#               schema licence (OASIS permissive: use/copy/modify/distribute
#               with notice). Instances are referenced in place from
#               testdata/xsltng (DocBook xslTNG, MIT), not copied.
#
# Needs: sh, curl, unzip, tar, go, a C compiler (cc), shasum or sha256sum.
set -eu

ROOT=$(cd "$(dirname "$0")/.." && pwd)
OUT=$ROOT/testdata/bench
DL=$OUT/.download
mkdir -p "$DL"

die() { echo "fetch-inputs: $*" >&2; exit 1; }

sha256() {
	if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | cut -d' ' -f1
	else shasum -a 256 "$1" | cut -d' ' -f1; fi
}

# fetch URL SHA256 FILE -- download into $DL unless present with the right hash.
fetch() {
	f=$DL/$3
	if [ -f "$f" ] && [ "$(sha256 "$f")" = "$2" ]; then return 0; fi
	echo "fetch  $1"
	curl -fsSL --retry 3 -o "$f.part" "$1" || die "download failed: $1"
	got=$(sha256 "$f.part")
	[ "$got" = "$2" ] || { rm -f "$f.part"; die "checksum mismatch for $1: got $got want $2"; }
	mv "$f.part" "$f"
}

# unpack ARCHIVE DIR -- extract once per archive hash (stamp in DIR).
unpack() {
	want=$(sha256 "$DL/$1")
	if [ -f "$2/.stamp" ] && [ "$(cat "$2/.stamp")" = "$want" ]; then return 0; fi
	rm -rf "$2"; mkdir -p "$2"
	case $1 in
	*.zip) unzip -q "$DL/$1" -d "$2" ;;
	*.tar.gz) tar xzf "$DL/$1" -C "$2" ;;
	esac
	echo "$want" > "$2/.stamp"
}

fetch https://github.com/itplr-kosit/xrechnung-visualization/releases/download/v2026-08-31/xrechnung-3.0.2-visualization-2026-08-31.zip \
	1a6fa4ea26d777e2c7ee3af42f682ef4774bf00acf860a441e0cfc43dc6ae9e1 xrechnung-visualization.zip
fetch https://github.com/itplr-kosit/xrechnung-testsuite/releases/download/v2026-08-31/xrechnung-3.0.2-testsuite-2026-08-31.zip \
	1e81ef7563e0fa04c0e0b0631318a7e0843a3c0beb57d83ef95ac0c4a095e3d7 xrechnung-testsuite.zip
fetch https://github.com/OpenPEPPOL/peppol-bis-invoice-3/archive/refs/tags/v3.0.20.tar.gz \
	54b9ada9b866338c629789d30593162f90f1d76654d978266244932aabe02802 peppol-bis-invoice-3.tar.gz
fetch https://codeberg.org/SchXslt/schxslt/releases/download/v1.10.1/schxslt-1.10.1-xslt-only.zip \
	e141fabd4804a0ea527945dc7253dd38f9ef8957d9b219b94e13d16859cff7f0 schxslt.zip
fetch https://projects.cwi.nl/xmark/Assets/unix.c \
	12f08c20dbcf91e9d7149ffa3d6fb6ba42d5a447940f2294f4c8c7f5d5197bda xmlgen-unix.c
fetch https://projects.cwi.nl/xmark/Assets/xmlquery.txt \
	53168d556f9b665d7693ed9fde661c8f68f9a60ad4196d829a27a35b10a40791 xmlquery.txt
fetch https://projects.cwi.nl/xmark/Assets/auction.dtd \
	994e9a6fb8b9a9a3c1301fe68ff26ab7ddc4c0590619e68abb9d4b8f02076f62 auction.dtd
fetch https://github.com/docbook/docbook/releases/download/5.2/docbook-5.2.zip \
	11992554a884786f1b78c6b478d6cec90352caf00bef54731c8d54f26751f2c5 docbook-5.2.zip

GOXML=$DL/go-xml
(cd "$ROOT" && go build -o "$GOXML" ./cmd/go-xml) || die "cannot build go-xml"

# 1. XRechnung: stylesheets as released, 8 UBL invoices from the testsuite.
unpack xrechnung-visualization.zip "$DL/xrv"
unpack xrechnung-testsuite.zip "$DL/xrts"
rm -rf "$OUT/xrechnung"; mkdir -p "$OUT/xrechnung/invoices"
cp -R "$DL/xrv/xsl" "$OUT/xrechnung/xsl"
for n in 01.01a 01.05a 01.06a 01.13a 01.15a 02.01a 03.01a 03.07a; do
	cp "$DL/xrts/instances/standard/$n-INVOICE_ubl.xml" "$OUT/xrechnung/invoices/"
done

# 2. Peppol BIS Billing 3.0: CEN + PEPPOL UBL Schematron, compiled with SchXslt.
unpack peppol-bis-invoice-3.tar.gz "$DL/peppol"
unpack schxslt.zip "$DL/schxslt"
P=$DL/peppol/peppol-bis-invoice-3-3.0.20/rules
rm -rf "$OUT/peppol"; mkdir -p "$OUT/peppol/sch" "$OUT/peppol/xsl" "$OUT/peppol/invoices"
cp "$P"/examples/*.xml "$OUT/peppol/invoices/"
SAXON_JAR=${SAXON_JAR:-$(ls "$ROOT"/bench/.cache/*/[Ss]axon-[Hh][Ee]-*.jar "$ROOT"/bench/.cache/[Ss]axon-[Hh][Ee]-*.jar 2>/dev/null | head -n 1 || true)}
SCH_ROUTE=""
for s in CEN-EN16931-UBL PEPPOL-EN16931-UBL; do
	cp "$P/sch/$s.sch" "$OUT/peppol/sch/"
	# -now pins the dct:created stamp SchXslt writes, so reruns are byte-identical.
	if "$GOXML" -xsl "$DL/schxslt/schxslt-1.10.1/2.0/pipeline-for-svrl.xsl" -now 2026-03-16T00:00:00Z \
		-o "$OUT/peppol/xsl/$s.xsl" "$OUT/peppol/sch/$s.sch" 2>"$DL/sch-$s.err"; then
		SCH_ROUTE="$SCH_ROUTE $s:go-xml"
	elif [ -n "$SAXON_JAR" ]; then
		echo "go-xml could not compile $s ($(head -n 1 "$DL/sch-$s.err")); using $SAXON_JAR"
		java -jar "$SAXON_JAR" -s:"$OUT/peppol/sch/$s.sch" -xsl:"$DL/schxslt/schxslt-1.10.1/2.0/pipeline-for-svrl.xsl" \
			-o:"$OUT/peppol/xsl/$s.xsl" || die "Saxon could not compile $s"
		SCH_ROUTE="$SCH_ROUTE $s:saxon"
	else
		die "go-xml could not compile $s and no Saxon jar is available: $(cat "$DL/sch-$s.err")"
	fi
done

# 3. XMark: build xmlgen, generate three scale factors, split the 20 queries.
X=$OUT/xmark
mkdir -p "$X/queries"
cp "$DL/xmlgen-unix.c" "$DL/auction.dtd" "$X/"
if [ ! -x "$DL/xmlgen" ]; then
	# macOS with an unaccepted Xcode licence still has a working CommandLineTools cc.
	cc -O2 -w -o "$DL/xmlgen" "$DL/xmlgen-unix.c" -lm 2>/dev/null ||
		DEVELOPER_DIR=/Library/Developer/CommandLineTools cc -O2 -w -o "$DL/xmlgen" "$DL/xmlgen-unix.c" -lm ||
		die "cannot compile xmlgen"
fi
for f in 0.01 0.1 1; do
	[ -s "$X/auction-$f.xml" ] || "$DL/xmlgen" -f "$f" -o "$X/auction-$f.xml"
done
# Convention: the auction document is the context item, so doc("auction.xml")
# becomes "." -- run as: go-xml xquery -q qN.xq auction-F.xml
awk -v dir="$X/queries" '
/^-- Q[0-9]+/ { if (f) close(f); n = $2; sub(/^Q/, "", n); sub(/\..*/, "", n); f = dir "/q" n ".xq"; printf "" > f }
!f { next }
/^--/ { l = $0; sub(/^-- ?/, "", l); print "(: " l " :)" > f; next }
{ gsub(/doc\("auction\.xml"\)/, "."); print > f }' "$DL/xmlquery.txt"
XQ_FAIL=""
for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do
	"$GOXML" xquery -q "$X/queries/q$i.xq" "$X/auction-0.01.xml" >/dev/null 2>"$DL/xq.err" ||
		XQ_FAIL="$XQ_FAIL
- q$i: $(head -n 1 "$DL/xq.err")"
done

# 4. Large parse inputs, deterministic (bench/gen, seed 20261007).
mkdir -p "$OUT/parse"
for s in 1 10 100; do
	[ -s "$OUT/parse/parse-${s}mb.xml" ] ||
		(cd "$ROOT" && go run ./bench/gen -size "${s}000000" -o "$OUT/parse/parse-${s}mb.xml")
done

# 5. RELAX NG: DocBook 5.2 schemas; xslTNG instances referenced by path.
unpack docbook-5.2.zip "$DL/docbook"
rm -rf "$OUT/docbook"; mkdir -p "$OUT/docbook"
cp -R "$DL/docbook/docbook-5.2/rng" "$OUT/docbook/rng"
TNG=testdata/xsltng/src/test/resources/xml
if [ -d "$ROOT/$TNG" ]; then
	(cd "$ROOT" && grep -l 'xmlns="http://docbook.org/ns/docbook"' "$TNG"/*.xml | LC_ALL=C sort) > "$OUT/docbook/documents.txt"
else
	echo "warning: $TNG missing; docbook/documents.txt is empty" >&2
	: > "$OUT/docbook/documents.txt"
fi

# SOURCES.md
{
cat <<'EOF'
# Benchmark inputs (generated by bench/fetch-inputs.sh -- do not edit)

| Dir | Source | Pin | Licence |
|-----|--------|-----|---------|
| xrechnung/xsl | KoSIT xrechnung-visualization | v2026-08-31, commit e158048ec6774cd4837744b21ca34dc95ba14862, zip sha256 1a6fa4ea26d777e2c7ee3af42f682ef4774bf00acf860a441e0cfc43dc6ae9e1 | Apache-2.0 |
| xrechnung/invoices | KoSIT xrechnung-testsuite, instances/standard/*_ubl.xml (8) | v2026-08-31, commit 44c3905c69ca236aa3b94c04be1b7e9bd066ba03, zip sha256 1e81ef7563e0fa04c0e0b0631318a7e0843a3c0beb57d83ef95ac0c4a095e3d7 | Apache-2.0 |
| peppol/sch, peppol/invoices | OpenPEPPOL peppol-bis-invoice-3, rules/sch, rules/examples | v3.0.20, commit 261c458474e27d58a25be629cccac28883171c92, tar.gz sha256 54b9ada9b866338c629789d30593162f90f1d76654d978266244932aabe02802 | no licence file; CEN rules EUPL-1.2; PEPPOL rules (c) OpenPeppol, no redistribution without consent -- never commit |
| peppol/xsl | compiled by SchXslt 2.0/pipeline-for-svrl.xsl | SchXslt 1.10.1, commit 17f63a42c2d417206e1289cf767359c4fa047919, zip sha256 e141fabd4804a0ea527945dc7253dd38f9ef8957d9b219b94e13d16859cff7f0 | MIT (SchXslt); output inherits the rules' terms |
| xmark | CWI XMark xmlgen unix.c, xmlquery.txt, auction.dtd | unix.c 12f08c20dbcf91e9d7149ffa3d6fb6ba42d5a447940f2294f4c8c7f5d5197bda, xmlquery.txt 53168d556f9b665d7693ed9fde661c8f68f9a60ad4196d829a27a35b10a40791, auction.dtd 994e9a6fb8b9a9a3c1301fe68ff26ab7ddc4c0590619e68abb9d4b8f02076f62 | xmlgen public domain (CWI downloads page); queries/DTD: none stated |
| parse | bench/gen in this repository, seed 20261007 | generated | MIT |
| docbook/rng | DocBook 5.2 release | tag 5.2, commit 7bf26df21266c00d38ea1d3033bcd70c2b280a59, zip sha256 11992554a884786f1b78c6b478d6cec90352caf00bef54731c8d54f26751f2c5 | DocBook schema licence (OASIS, permissive with notice) |
| docbook/documents.txt | paths of DocBook 5 instances in testdata/xsltng (xslTNG, MIT), not copied | testdata/xsltng checkout | MIT |

## XRechnung chain (UBL -> HTML)

1. `xrechnung/xsl/ubl-invoice-xr.xsl` on a UBL Invoice -> intermediate `xr:invoice` XML.
2. `xrechnung/xsl/xrechnung-html.xsl` on that XML -> HTML. Parameters: `lang`
   (default `de`; `en` also shipped), `l10n-nl-lookup` (default `true()`).
   It reads `xrechnung-viewer.css`, `xrechnung-viewer.js` and
   `FileSaver-v2.0.5.js` with `unparsed-text()` (go-xml: `-allow-unparsed-text`)
   and `l10n/<lang>.xml`. CreditNote input would use `ubl-creditnote-xr.xsl`.
   Note: `xrechnung-html.xsl` (version 2.0) puts `xsl:output` before `xsl:import`.

## Peppol validation

Compile: `go-xml -xsl schxslt-1.10.1/2.0/pipeline-for-svrl.xsl -now 2026-03-16T00:00:00Z
-o peppol/xsl/<name>.xsl peppol/sch/<name>.sch`. Validate: apply `peppol/xsl/<name>.xsl`
to each `peppol/invoices/*.xml`; the result is SVRL. Both rule sets apply to every invoice.

## XMark convention

The auction document is the context item: every `doc("auction.xml")` in the
original xmlquery.txt is rewritten to `.`, and the `--` comment lines become
XQuery comments. Run `go-xml xquery -q xmark/queries/qN.xq xmark/auction-F.xml`
(Saxon: `-s:auction-F.xml -q:qN.xq`; BaseX: `-i auction-F.xml qN.xq`).

EOF
echo "Schematron compile route:$SCH_ROUTE"
echo
if [ -n "$XQ_FAIL" ]; then echo "XMark queries failing under go-xml on auction-0.01.xml:$XQ_FAIL"
else echo "XMark queries: q1..q20 all run under go-xml on auction-0.01.xml."; fi
echo
echo "## Generated files (sha256)"
echo
for f in "$X"/auction-*.xml "$OUT"/parse/*.xml "$OUT"/peppol/xsl/*.xsl; do
	echo "- ${f#"$OUT"/} $(sha256 "$f")"
done
echo
echo "DocBook instances listed: $(wc -l < "$OUT/docbook/documents.txt" | tr -d ' ')"
} > "$OUT/SOURCES.md"

# Summary
printf '\n%-34s %10s %6s\n' PATH KB FILES
for d in xrechnung/xsl xrechnung/invoices peppol/sch peppol/xsl peppol/invoices xmark xmark/queries parse docbook/rng; do
	printf '%-34s %10s %6s\n' "testdata/bench/$d" "$(du -sk "$OUT/$d" | cut -f1)" "$(find "$OUT/$d" -type f | wc -l | tr -d ' ')"
done
printf '%-34s %10s %6s\n' "docbook/documents.txt" "-" "$(wc -l < "$OUT/docbook/documents.txt" | tr -d ' ')"
echo "Schematron route:$SCH_ROUTE"
[ -z "$XQ_FAIL" ] || echo "XMark failures:$XQ_FAIL"
